Dockerfile

- Revert image, use alpine instead of distroless

Revert image, use alpine insted of distroless

---

.github/workflows/build.yaml

- FOSSA doesn't support scanning distroless https://github.com/fossas/fossa-cli/issues/1093
We still have FOSSA running on main branch/PR and also every 12h to scan

chore: FOSSA image scan not supported for distroless images

---

actions/delete_node_handler.go
actions/delete_node_handler_test.go
castai/types.go

Skip node delete when node_id mismatch for case where cloud reuses the names

CORE-3242: skip node delete on id mismatch

---

go.mod
go.sum
main.go

Unifies logging by adding logging adapter for glog (which is base for klog) so we send logs to mothership. 
Currently when go-client logs errors we are not sending those and its hard to build full picture of what is happening.

CORE-3320: Add klog to logrus adapter 

---

main.go

For the sake of debugability, try to log the real reason of shutting down the controller instead of always logging `leader lost` that could be misleading.

Log real reason of shutdown of the controller.

---

actions/kubernetes_helpers.go
actions/patch_node_handler.go

Defensive programming. If `casai-cluster-controller` was upgraded but permission to Patch `node/status` were not added we don't won't to fail the whole action.

KUBE-194: permissions might not be upgraded yet so silence forbidden error

---

README.md
actions/actions.go
hack/remote/deploy.sh

Server expects structured log fields to be `map[string]string` so for now explicitly converting values to string to avoid BAD_REQUEST/400 errors.

sent log fields values must be strings otherwise 400

---

.github/workflows/build.yaml
.github/workflows/golangci-lint.yaml
go.mod

chore: bump golang version to 1.22

---

actions/delete_node_handler_test.go
actions/drain_node_handler.go
actions/drain_node_handler_test.go

Main change - treat PDB violation errors during eviction as non-retryable. Sometimes the PDB can never be satisfied if we evict a pod so we'd be stuck in infinite retry. 
Additional changes:
- Fixed a bug where CAST pods were added to the eviction list twice - so they weren't evicted last correctly. 
- Changed the batching implementation with channel + workers. This does not guarantee 100% that pod operations can't get stuck but a single one won't block others (as it was before - a single infinite retry blocks all chunks after it). If we get #InfiniteRetries > #Tasks, we'd still be stuck but the chances are much lower. 
- Added some additional logging here and there for future debuggability

KUBE-479: Evict all pods even in case of PDB violations

---

actions/drain_node_handler.go

Adjustments to previous MR to make it more robust for the general use-case after internal discussion.
* Make PDB retryable to follow "evict-if-possible" logic for normal operations
* Bump the parallel task limit for eviction/deletion. The biggest issue with retryable PDB is that we can get stuck retrying a pod that is never satisfied; therefore losing one of the goroutines. If all get stuck, we wouldn't send eviction requests to other pods. 30 tasks should be OK for a general case since most nodes seem to have 30-100 pods in total on average from our experience. We will probably remove this limit in a future PR entirely.

KUBE-479: Adjustments to PDB

---

actions/delete_node_handler.go
actions/drain_node_handler.go
actions/drain_node_handler_test.go
actions/kubernetes_helpers.go

PR attempts to provide more consistent drain semantics (and handle some edge cases). 
Overview of changes:
1. Previously any pod that hit a non-retryable failure during eviction caused the error to surface and stop further processing. Now we will continue with forced deletion so one pod won't affect the overall flow (but we still surface an error at the end). 
2. In addition to 1), pods where DELETE/EVICT failed are not waited for termination. Otherwise we are stuck waiting for something that won't happen. 
3. For deletions, we follow the same logic as 1) - a single failed pod doesn't stop us retrying deletion ungracefully. 
4. Removed drainTimeout adjustment that was adding 10s on top (Discussed with Marcin; looks obsolete) 
5. Pods that are finished but Failed are also ignored for …

KUBE-479: Eviction adjustments 

---

internal/actions/drain_node_handler_test.go
internal/actions/evict_pod_handler.go
internal/actions/evict_pod_handler_test.go
internal/castai/types.go
internal/controller/controller.go

A new action. It has some overlap with the current DrainNode action. I figured it should be OK given the small scope of this action (plus the change has no accidental impact on DrainNode action) but if you prefer to dry this up now, that's OK.

feat: Add EvictPod action

---

cmd/controller/run.go
internal/config/config.go
internal/config/config_test.go
internal/controller/controller.go
internal/controller/controller_test.go

Part of `KUBE-417`
The idea behind the change - safeguard on the CC to limit the amount of goroutines in progress. Currently there is no limit and CC will spawn whatever API will return.

feat: max actions in progress

---

.github/workflows/golangci-lint.yaml
Makefile
hack/go-install.sh
internal/actions/create_handler.go
internal/actions/create_handler_test.go
internal/actions/delete_handler.go
internal/actions/delete_handler_test.go

Small changes to allow to send create action with non-namespaced objects.
pattern is copy paste from other objects.

Support non-namespaces creates

---

cmd/controller/run.go
internal/config/config.go

- Made `Node` not required so one can run on local machine
- Adjusted namespace error because it was confusing that you need `LEADER_ELECTION_NAMESPACE` even when not using leader election. It's still used by components so I left it as required.

NOJIRA: Allow for easier local run.

---

Makefile
README.md
hack/loadtest/deploy.sh
hack/loadtest/grafana/cluster-controller-dashboard.json
hack/loadtest/grafana/dashboards-config.yaml
hack/loadtest/grafana/grafana.ini
hack/loadtest/grafana/prometheus-datasource.yaml
hack/loadtest/kustomization.yaml
hack/loadtest/loadtest-components.yaml
loadtest/README.md
loadtest/scenarios/k8s_objects.go

Adds the option to deploy CC + test server + kwok + observability stack in existing cluster, no need to manually run them locally. 
The deploy consists of:
- Cluster controller (via helm install), can be omitted
- Kwok controller (via helm install)
- Deployment for the test server (CC is already wired to use it)
- Deployment for prometheus/grafana, configured to scrape CC endpoint 
- RBAC for prometheus and test-server. 
Grafana also has preconfigured dashboards with several metrics, more can be added (should update the dashboard json under `hack/loadtest/grafana`:

Kube-984: loadtesting in cluster

---

internal/castai/client.go
internal/controller/logexporter/logexporter.go

Copies the logrus struct before calling our hook concurrently. 
This avoids a data race when we overwrite some map items in-place while logrus is reading the map. It also avoids a rarer data race where we read the `Message` on the entry while logrus' `TextFormatter` writes to it. 
First issue causes panics under load (concurrent map read/write), second one was more benign. 
Tested using `GORACE=halt_on_error=1 log_path=race.log" go run -race .` - no errors reported. 
Race.log before change when running with `GORACE=halt_on_error=1 log_path=race.log" go run -race .`:
```
==================
WARNING: DATA RACE
Read at 0x00c000272658 by goroutine 66:
github.com/castai/cluster-controller/internal/controller/logexporter.(*LogExporter).sendLogEvent() …
```

KUBE-627: Avoid data race panic in logexporter

---

internal/actions/delete_node_handler.go

Especially Pending pods from deployments can be problematic - even though we deleted them, they might end up back on the node if `nodeName` is set and be stuck in Pending state.

NOJIRA: Don't wait for non-running pods when deleting node.

---

cmd/testserver/run.go
hack/loadtest/deploy.sh
hack/loadtest/grafana/cluster-controller-dashboard.json
internal/metrics/metrics.go
loadtest/castai.go
loadtest/config.go
loadtest/scenarios/check_node_deleted_stuck.go
loadtest/scenarios/check_node_status.go
loadtest/scenarios/delete_node.go
loadtest/scenarios/drain_node.go
loadtest/scenarios/evict_pod.go
loadtest/scenarios/patch_node.go
loadtest/scenarios/stuck_drain.go
loadtest/scenarios/util.go

* Reworked the test server so it returns the same actions again if they are not completed instead of always pushing new ones to CC (as that is what CH does), still needs some adjustments in general to be feature-proof
* More tests create preparation in parallel now
* Certain node tests that can reuse the node for the same action do, to avoid creating many many resources just for prep work
* Adjusted grafana dashboard a bit in terms of timings

KUBE-984: Adjustments around running load tests

---

Makefile
internal/actions/csr/svc.go
internal/actions/csr/svc_test.go

On GKE 1.33 it was observed that the user has changed, causing CSR to not be recognized and ignored. Node was stuck unable to reach apiserver due to this. 
Also made the "skip" log info level as most customers deploy at info and it was impossible to see this was happening live.

CSU-3481: Add new bootstrap requesting user for CSR to auto-approval

---

internal/actions/evict_pod_handler.go
internal/actions/evict_pod_handler_test.go
internal/castai/types.go

In cases where we cannot evict pods (i.e. due to restrictive PDBs), we don't want these actions pending indefinitely.

CO-3733 Support timeout for EvictPod
